export const LOAD_MACHINE_ISSUES_FAILED = "LOAD_MACHINE_ISSUES_FAILED";
export const LOAD_MACHINE_ISSUES_SUCCESS = "LOAD_MACHINE_ISSUES_SUCCESS";
export const LOAD_MACHINE_ISSUES = "LOAD_MACHINE_ISSUES";
export const LOAD_MACHINE_DEPLOYMENTS_FAILED = "LOAD_MACHINE_DEPLOYMENTS_FAILED";
export const LOAD_MACHINE_DEPLOYMENTS_SUCCESS = "LOAD_MACHINE_DEPLOYMENTS_SUCCESS";
export const LOAD_MACHINE_DEPLOYMENTS = "LOAD_MACHINE_DEPLOYMENTS";

export const OPERATION_STARTED = "OPERATION_STARTED";
export const OPERATION_SUCCESSFUL = "OPERATION_SUCCESSFUL";
export const RESET_OPERATIONS = "RESET_OPERATIONS";
export const OPERATION_FAILED = "OPERATION_FAILED";
export const OPERATION_TIMEOUT = "OPERATION_TIMEOUT";

export const LOCK_SESSION = "LOCK_SESSION";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SOCKET_READY = "SOCKET_READY";

export const LOAD_MACHINES = "LOAD_MACHINES";
export const LOAD_MACHINES_SUCCESS = "LOAD_MACHINES_SUCCESS";
export const LOAD_MACHINES_FAILED = "LOAD_MACHINES_FAILED";

export const LOAD_MACHINE_LOGS = "LOAD_MACHINE_LOGS";
export const LOAD_MACHINE_LOGS_SUCCESS = "LOAD_MACHINE_LOGS_SUCCESS";
export const LOAD_MACHINE_LOGS_FAILED = "LOAD_MACHINE_LOGS_FAILED";

export const LOAD_MACHINE_PROFILE = "LOAD_MACHINE_PROFILE";
export const LOAD_MACHINE_PROFILE_SUCCESS = "LOAD_MACHINE_PROFILE_SUCCESS";
export const LOAD_MACHINE_PROFILE_FAILED = "LOAD_MACHINE_PROFILE_FAILED";

export const MACHINES_UPDATED = "MACHINES_UPDATED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SYSTEM_STATUS = "SYSTEM_STATUS";
export const START_APPLICATION = "START_APPLICATION";
export const START_SERVICE = "START_SERVICE";
export const STOP_APPLICATION = "STOP_APPLICATION";
export const STOP_SERVICE = "STOP_SERVICE";
export const SHUT_DOWN = "SHUT_DOWN";
export const RESTART = "RESTART";

export const CHANGE_PASSWORD_DONE = "CHANGE_PASSWORD_DONE";
export const NETWORK_STATUS_CHANGED = "NETWORK_STATUS_CHANGED";
export const NETWORK_STATUS = "NETWORK_STATUS";
export const USER_ACTIVITY_CHANGED = "USER_ACTIVITY_CHANGED";
export const APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED";
export const APPLICATIONS_STATUS = "APPLICATIONS_STATUS";
export const SERVICE_STATUS_CHANGED = "SERVICE_STATUS_CHANGED";
export const SERVICES_STATUS = "SERVICES_STATUS";
export const LOCATION_STATUS_CHANGED = "LOCATION_STATUS_CHANGED";
export const LOCATION_STATUS = "LOCATION_STATUS";
export const LOCATION_MONITOR = "LOCATION_MONITOR";
export const LOCATION_MONITOR_STOP = "LOCATION_MONITOR_STOP";
export const SYSTEM_MONITOR = "SYSTEM_MONITOR";
export const SYSTEM_MONITOR_STOP = "SYSTEM_MONITOR_STOP";
