export const LOAD_MRW_ISSUES_FAILED = "LOAD_MRW_ISSUES_FAILED";
export const LOAD_MRW_ISSUES_SUCCESS = "LOAD_MRW_ISSUES_SUCCESS";
export const LOAD_MRW_ISSUES = "LOAD_MRW_ISSUES";
export const LOAD_MRW_DEPLOYMENTS_FAILED = "LOAD_MRW_DEPLOYMENTS_FAILED";
export const LOAD_MRW_DEPLOYMENTS_SUCCESS = "LOAD_MRW_DEPLOYMENTS_SUCCESS";
export const LOAD_MRW_DEPLOYMENTS = "LOAD_MRW_DEPLOYMENTS";

export const OPERATION_SUCCESSFUL = "OPERATION_SUCCESSFUL";
export const RESET_OPERATIONS = "RESET_OPERATIONS";
export const OPERATION_FAILED = "OPERATION_FAILED";

export const LOCK_SESSION = "LOCK_SESSION";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOAD_MRWS = "LOAD_MRWS";
export const LOAD_MRWS_SUCCESS = "LOAD_MRWS_SUCCESS";
export const LOAD_MRWS_FAILED = "LOAD_MRWS_FAILED";

export const LOAD_MRW_LOGS = "LOAD_MRW_LOGS";
export const LOAD_MRW_LOGS_SUCCESS = "LOAD_MRW_LOGS_SUCCESS";
export const LOAD_MRW_LOGS_FAILED = "LOAD_MRW_LOGS_FAILED";

export const LOAD_MRW_INFORMATION = "LOAD_MRW_INFORMATION";
export const LOAD_MRW_INFORMATION_SUCCESS = "LOAD_MRW_INFORMATION_SUCCESS";
export const LOAD_MRW_INFORMATION_FAILED = "LOAD_MRW_INFORMATION_FAILED";

export const MRW_UPDATED = "MRW_UPDATED";