export const LOAD_POLICIES = "LOAD_POLICIES";
export const LOAD_POLICIES_SUCCESSFUL = "LOAD_POLICIES_SUCCESSFUL";
export const LOAD_POLICIES_FAILED = "LOAD_POLICIES_FAILED";
export const LOAD_ROLE_POLICIES = "LOAD_ROLE_POLICIES";
export const LOAD_ROLE_POLICIES_SUCCESSFUL = "LOAD_ROLE_POLICIES_SUCCESSFUL";
export const LOAD_ROLE_POLICIES_FAILED = "LOAD_ROLE_POLICIES_FAILED";
export const ADD_POLICY = "ADD_POLICY";
export const ADD_POLICY_SUCCESSFUL = "ADD_POLICY_SUCCESSFUL";
export const ADD_POLICY_FAILED = "ADD_POLICY_FAILED";
export const EDIT_POLICY = "EDIT_POLICY";
export const EDIT_POLICY_SUCCESSFUL = "EDIT_POLICY_SUCCESSFUL";
export const EDIT_POLICY_FAILED = "EDIT_POLICY_FAILED";
export const DELETE_POLICY = "DELETE_POLICY";
export const DELETE_POLICY_SUCCESSFUL = "DELETE_POLICY_SUCCESSFUL";
export const DELETE_POLICY_FAILED = "DELETE_POLICY_FAILED";

export const LOAD_ROLES = "LOAD_ROLES";
export const LOAD_ROLES_SUCCESSFUL = "LOAD_ROLES_SUCCESSFUL";
export const LOAD_ROLES_FAILED = "LOAD_ROLES_FAILED";
export const ADD_ROLE = "ADD_ROLE";
export const ADD_ROLE_SUCCESSFUL = "ADD_ROLE_SUCCESSFUL";
export const ADD_ROLE_FAILED = "ADD_ROLE_FAILED";
export const EDIT_ROLE = "EDIT_ROLE";
export const EDIT_ROLE_SUCCESSFUL = "EDIT_ROLE_SUCCESSFUL";
export const EDIT_ROLE_FAILED = "EDIT_ROLE_FAILED";
export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESSFUL = "DELETE_ROLE_SUCCESSFUL";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";
export const LOAD_PAGES = "LOAD_PAGES";
export const LOAD_PAGES_SUCCESSFUL = "LOAD_PAGES_SUCCESSFUL";
export const LOAD_PAGES_FAILED = "LOAD_PAGES_FAILED";
export const LOAD_ENTITIES = "LOAD_ENTITIES";
export const LOAD_ENTITIES_SUCCESSFUL = "LOAD_ENTITIES_SUCCESSFUL";
export const LOAD_ENTITIES_FAILED = "LOAD_ENTITIES_FAILED";
export const LOAD_ACTIONS = "LOAD_ACTIONS";
export const LOAD_ACTIONS_SUCCESSFUL = "LOAD_ACTIONS_SUCCESSFUL";
export const LOAD_ACTIONS_FAILED = "LOAD_ACTIONS_FAILED";

export const EDIT_ROLE_WITH_USERS = "EDIT_ROLE_WITH_USERS";
export const EDIT_ROLE_WITH_POLICIES = "EDIT_ROLE_WITH_POLICIES";

export const LOAD_LOGS_SUCCESS = "LOAD_LOGS_SUCCESS";
export const LOAD_LOGS = "LOAD_LOGS";
export const LOAD_LOGS_FAILED = "LOAD_LOGS_FAILED";
export const EXPORT_LOGS = "EXPORT_LOGS";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const EXPORT_LOGS_SUCCESS = "EXPORT_LOGS_SUCCESS";
export const EXPORT_LOGS_FAILED = "EXPORT_LOGS_FAILED";

export const PDF = "PDF";
export const DOWNLOAD_SUCCESS = "DOWNLOAD_SUCCESS";
export const GZIP = "GZIP";
export const SHEET = "SHEET";

export const LOAD_USERS = "LOAD_USERS";
export const LOAD_USERS_SUCCESSFUL = "LOAD_USERS_SUCCESSFUL";
export const LOAD_USERS_FAILED = "LOAD_USERS_FAILED";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESSFUL = "ADD_USER_SUCCESSFUL";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESSFUL = "DELETE_USER_SUCCESSFUL";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const LOAD_MACHINE_ISSUES_FAILED = "LOAD_MACHINE_ISSUES_FAILED";
export const LOAD_MACHINE_ISSUES_SUCCESS = "LOAD_MACHINE_ISSUES_SUCCESS";
export const LOAD_MACHINE_ISSUES = "LOAD_MACHINE_ISSUES";
export const LOAD_MACHINE_DEPLOYMENTS_FAILED = "LOAD_MACHINE_DEPLOYMENTS_FAILED";
export const LOAD_MACHINE_DEPLOYMENTS_SUCCESS = "LOAD_MACHINE_DEPLOYMENTS_SUCCESS";
export const LOAD_MACHINE_DEPLOYMENTS = "LOAD_MACHINE_DEPLOYMENTS";

export const OPERATION_STARTED = "OPERATION_STARTED";
export const OPERATION_SUCCESSFUL = "OPERATION_SUCCESSFUL";
export const RESET_OPERATIONS = "RESET_OPERATIONS";
export const OPERATION_FAILED = "OPERATION_FAILED";
export const OPERATION_TIMEOUT = "OPERATION_TIMEOUT";

export const LOCK_SESSION = "LOCK_SESSION";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SOCKET_READY = "SOCKET_READY";

export const LOAD_MACHINES = "LOAD_MACHINES";
export const LOAD_MACHINES_SUCCESS = "LOAD_MACHINES_SUCCESS";
export const LOAD_MACHINES_FAILED = "LOAD_MACHINES_FAILED";

export const LOAD_MACHINE_LOGS = "LOAD_MACHINE_LOGS";
export const LOAD_MACHINE_LOGS_SUCCESS = "LOAD_MACHINE_LOGS_SUCCESS";
export const LOAD_MACHINE_LOGS_FAILED = "LOAD_MACHINE_LOGS_FAILED";

export const LOAD_MACHINE_PROFILE = "LOAD_MACHINE_PROFILE";
export const LOAD_MACHINE_PROFILE_SUCCESS = "LOAD_MACHINE_PROFILE_SUCCESS";
export const LOAD_MACHINE_PROFILE_FAILED = "LOAD_MACHINE_PROFILE_FAILED";

export const MACHINES_UPDATED = "MACHINES_UPDATED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SYSTEM_STATUS = "SYSTEM_STATUS";
export const START_APPLICATION = "START_APPLICATION";
export const START_SERVICE = "START_SERVICE";
export const STOP_APPLICATION = "STOP_APPLICATION";
export const STOP_SERVICE = "STOP_SERVICE";
export const SHUT_DOWN = "SHUT_DOWN";
export const RESTART = "RESTART";

export const CHANGE_PASSWORD_DONE = "CHANGE_PASSWORD_DONE";
export const NETWORK_STATUS_CHANGED = "NETWORK_STATUS_CHANGED";
export const NETWORK_STATUS = "NETWORK_STATUS";
export const USER_ACTIVITY_CHANGED = "USER_ACTIVITY_CHANGED";
export const APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED";
export const APPLICATIONS_STATUS = "APPLICATIONS_STATUS";
export const SERVICE_STATUS_CHANGED = "SERVICE_STATUS_CHANGED";
export const SERVICES_STATUS = "SERVICES_STATUS";
export const LOCATION_STATUS_CHANGED = "LOCATION_STATUS_CHANGED";
export const LOCATION_STATUS = "LOCATION_STATUS";
export const LOCATION_MONITOR = "LOCATION_MONITOR";
export const LOCATION_MONITOR_STOP = "LOCATION_MONITOR_STOP";
export const SYSTEM_MONITOR = "SYSTEM_MONITOR";
export const SYSTEM_MONITOR_STOP = "SYSTEM_MONITOR_STOP";
